##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-sc-trim
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  io_profile: "db_remote"
  nodiscard: "true"
allowVolumeExpansion: true
---
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fio-log-trim
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "high"
  io_profile: "db_remote"
  nodiscard: "true"
allowVolumeExpansion: true
