##### Portworx Pure storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nginx-sc
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashBlade Direct Access
  backend: "pure_file"
allowVolumeExpansion: true
