apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-job-config
data:
  fio.job: |
    [global]
    name=fio-rand-W
    filename=/scratch/fio.dat
    rw=write
    randrepeat=1
    end_fsync=1
    disable_lat=0
    time_based=1
    runtime=99999999
    blocksize=4k
    size=50GB
    ioengine=libaio
    direct=1
    gtod_reduce=1
    iodepth=128
    [file1]
    ioengine=libaio
