##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  backend: "pure_block"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc-aggr
provisioner: kubernetes.io/portworx-volume
parameters:
  backend: "pure_block"
  csi.storage.k8s.io/fstype: ext4
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc-seq
provisioner: kubernetes.io/portworx-volume
parameters:
  backend: "pure_block"
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
