apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc-legacy-shared
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashArray Direct Access w/ filesystem
  # * Default filesystem type (ext4), mount options and create options
  # * No QoS
  backend: "pure_file"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashArray Direct Access w/ filesystem
  # * Default filesystem type (ext4), mount options and create options
  # * No QoS
  backend: "pure_block"
allowVolumeExpansion: true
