apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc-legacy-shared
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  max_iops: "30000"
  max_bandwidth: "10G"
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc
provisioner: pxd.portworx.com
parameters:
  backend: "pure_block"
  max_iops: "30000"
  max_bandwidth: "10G"
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
