##### Portworx Pure storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nginx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  backend: "pure_block"
  iops_limit: "30000"
  bandwidth_limit: "10G"
  csi.storage.k8s.io/fstype: xfs
allowVolumeExpansion: true
