kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: elasticsearch-sc
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashArray Direct Access w/ filesystem
  # * Default filesystem type (XFS), mount options and create options
  # * No QoS
  backend: "pure_block"
allowVolumeExpansion: true
